name: validate-apex-code
on: [push]
jobs:
  check-apex:
    runs-on: ubuntu-latest
     steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '11'
  - uses: pmd/pmd-github-action@v1
    id: pmd
    with:
      version: '6.40.0'
      sourcePath: 'force-app/main/default/classes'
      rulesets: 'scripts/abc.xml'
  - name: Fail build if there are violations
    if: steps.pmd.outputs.violations != 0
    run: exit 1
