name: PMD source check
on: [push]
jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krukmat/setup-pmd@v0.4
      - run: npm run apex-pmd
      
BEGIN PACKAGE.JSON FILE
{
  "scripts": {
    "apex-pmd": "pmd -d force-app/main/default -R scripts/abc.xml -f text"
  },
}
